/** Witnext JSON backup — table registry (metadata only, no Storage egress). */

export const BACKUP_FORMAT_VERSION = 6;

export type BackupFetchMode = 'serial_id' | 'uuid_created';

/** Core tables exported since v5 (inventory + auth snapshot). */
export const BACKUP_CORE_TABLES: readonly string[] = [
  'clients',
  'fournisseurs',
  'documents',
  'devis',
  'orders',
  'product_groups',
  'products',
  'product_group_fournisseurs',
  'transactions',
  'profiles',
  'user_roles',
  'user_presence',
  'team_chat_messages',
] as const;

/** Extended tables added in v6 (gallery, finance, RH, commercial, fleet). */
export const BACKUP_EXTENDED_TABLES: readonly { table: string; mode: BackupFetchMode }[] = [
  { table: 'companies', mode: 'uuid_created' },
  { table: 'category_settings', mode: 'serial_id' },
  { table: 'gallery_categories', mode: 'serial_id' },
  { table: 'gallery_items', mode: 'serial_id' },
  { table: 'document_lines', mode: 'serial_id' },
  { table: 'bons_commande', mode: 'serial_id' },
  { table: 'echantillons', mode: 'serial_id' },
  { table: 'factures', mode: 'serial_id' },
  { table: 'parties_suivi', mode: 'uuid_created' },
  { table: 'rdvs', mode: 'uuid_created' },
  { table: 'devis_helper_mappings', mode: 'serial_id' },
  { table: 'user_section_permissions', mode: 'serial_id' },
  { table: 'hr_employees', mode: 'uuid_created' },
  { table: 'hr_employee_leaves', mode: 'uuid_created' },
  { table: 'hr_payroll_movements', mode: 'uuid_created' },
  { table: 'rh_security_reports', mode: 'uuid_created' },
  { table: 'employees', mode: 'serial_id' },
  { table: 'vehicles', mode: 'uuid_created' },
  { table: 'vehicle_reminders', mode: 'uuid_created' },
  { table: 'fuel_vouchers', mode: 'uuid_created' },
  { table: 'invoices', mode: 'uuid_created' },
  { table: 'invoice_lines', mode: 'serial_id' },
  { table: 'payments', mode: 'uuid_created' },
  { table: 'payment_invoice_allocations', mode: 'uuid_created' },
  { table: 'journal_entries', mode: 'uuid_created' },
  { table: 'journal_lines', mode: 'serial_id' },
  { table: 'tax_declarations', mode: 'uuid_created' },
  { table: 'treasury_movements', mode: 'uuid_created' },
  { table: 'treasury_accounts', mode: 'uuid_created' },
  { table: 'treasury_transfers', mode: 'uuid_created' },
  { table: 'finance_avoirs', mode: 'uuid_created' },
  { table: 'finance_avoirs_article', mode: 'uuid_created' },
  { table: 'withholding_certificates', mode: 'uuid_created' },
  { table: 'bank_fee_types', mode: 'uuid_created' },
  { table: 'bank_fees', mode: 'uuid_created' },
  { table: 'bank_statement_lines', mode: 'uuid_created' },
  { table: 'leasing_credit_contracts', mode: 'uuid_created' },
  { table: 'payroll_periods', mode: 'uuid_created' },
  { table: 'payroll_slips', mode: 'uuid_created' },
  { table: 'commercial_dossiers', mode: 'uuid_created' },
  { table: 'commercial_dossier_events', mode: 'uuid_created' },
  { table: 'commercial_dossier_checkpoints', mode: 'uuid_created' },
  { table: 'app_config', mode: 'serial_id' },
  { table: 'user_companies', mode: 'uuid_created' },
];

/** FK-safe upsert order for v6 extended restore (after core inventory import). */
export const BACKUP_EXTENDED_IMPORT_ORDER: readonly string[] = BACKUP_EXTENDED_TABLES.map((t) => t.table);

export const BACKUP_COMPANY_SCOPED_TABLES = new Set([
  'clients',
  'fournisseurs',
  'product_groups',
  'products',
  'transactions',
  'documents',
  'orders',
  'devis',
  'gallery_items',
  'document_lines',
  'bons_commande',
  'echantillons',
  'factures',
  'parties_suivi',
  'rdvs',
  'hr_employees',
  'hr_employee_leaves',
  'hr_payroll_movements',
  'vehicles',
  'vehicle_reminders',
  'fuel_vouchers',
  'invoices',
  'invoice_lines',
  'payments',
  'payment_invoice_allocations',
  'journal_entries',
  'journal_lines',
  'tax_declarations',
  'treasury_movements',
  'treasury_accounts',
  'treasury_transfers',
  'finance_avoirs',
  'finance_avoirs_article',
  'withholding_certificates',
  'bank_fee_types',
  'bank_fees',
  'bank_statement_lines',
  'leasing_credit_contracts',
  'payroll_periods',
  'payroll_slips',
  'commercial_dossiers',
  'commercial_dossier_events',
  'commercial_dossier_checkpoints',
]);

/** Optional upsert conflict targets beyond primary key. */
export const BACKUP_UPSERT_CONFLICT: Record<string, string> = {
  profiles: 'user_id',
  user_roles: 'user_id,role',
  product_groups: 'company_id,name,category',
  product_group_fournisseurs: 'product_group_id,fournisseur_name',
  category_settings: 'category_name',
  user_presence: 'user_id',
  user_companies: 'user_id,company_id',
  gallery_categories: 'name',
  companies: 'code',
  app_config: 'key',
};
