
CREATE TABLE public.echantillons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  devis_id integer NOT NULL REFERENCES public.devis(id) ON DELETE CASCADE,
  product_name text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'envoyé',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.echantillons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read echantillons"
  ON public.echantillons FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert echantillons"
  ON public.echantillons FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update echantillons"
  ON public.echantillons FOR UPDATE TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can delete echantillons"
  ON public.echantillons FOR DELETE TO authenticated
  USING (true);
