// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnujsdxbkndvppjqjkdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJudWpzZHhia25kdnBwanFqa2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwNzg2OTIsImV4cCI6MjA5MTY1NDY5Mn0.AZWH1TFvBZR-Obwaz4sYNlLggrsKJYrqfZ5MjhdltCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});